import json
import re
from typing import Any


class JSONParser:
    """
    Utility responsible for extracting valid JSON from
    language model responses.

    Some LLMs wrap JSON inside Markdown code blocks or
    prepend explanatory text. This parser normalizes the
    response before decoding it.
    """

    @staticmethod
    def parse(
        response: str,
    ) -> dict[str, Any]:
        """
        Extracts and parses the first JSON object found
        in the response.

        Args:
            response:
                Raw text returned by the language model.

        Returns:
            Parsed JSON object.

        Raises:
            ValueError:
                If no valid JSON object can be extracted.
        """

        cleaned = response.strip()

        cleaned = re.sub(
            r"^```(?:json)?",
            "",
            cleaned,
            flags=re.IGNORECASE | re.MULTILINE,
        )

        cleaned = re.sub(
            r"```$",
            "",
            cleaned,
            flags=re.MULTILINE,
        ).strip()

        start = cleaned.find("{")
        end = cleaned.rfind("}")

        if start == -1 or end == -1:
            raise ValueError(
                "No JSON object found in LLM response."
            )

        json_text = cleaned[start : end + 1]

        try:
            return json.loads(json_text)

        except json.JSONDecodeError as exc:
            raise ValueError(
                "Invalid JSON generated by LLM."
            ) from exc
