from app.application.ports.llm_port import LLMPort
from app.infrastructure.ai.rag.prompt_builder import PromptBuilder
from app.infrastructure.ai.rag.retriever import Retriever


class AskQuestionUseCase:
    """
    Coordinates the complete Retrieval-Augmented Generation (RAG)
    workflow for answering a user's question.
    """

    def __init__(
        self,
        retriever: Retriever,
        prompt_builder: PromptBuilder,
        llm: LLMPort,
    ) -> None:
        self._retriever = retriever
        self._prompt_builder = prompt_builder
        self._llm = llm

    def execute(
        self,
        question: str,
    ) -> str:
        """
        Executes the complete RAG pipeline.

        Args:
            question: User question.

        Returns:
            Final answer generated by the language model.
        """

        contexts = self._retriever.retrieve(question)

        system_prompt, user_prompt = self._prompt_builder.build(
            question=question,
            contexts=contexts,
        )

        return self._llm.generate(
            prompt=user_prompt,
            system_prompt=system_prompt,
        )
