from typing import Any

from app.application.ports.llm_port import LLMPort
from app.infrastructure.ai.json_parser import JSONParser
from app.infrastructure.ai.prompts.exam_prompt_builder import (
    ExamPromptBuilder,
)
from app.infrastructure.ai.rag.retriever import Retriever


class GenerateExamUseCase:
    """
    Coordinates the complete Retrieval-Augmented Generation
    workflow for generating academic exams.
    """

    def __init__(
        self,
        retriever: Retriever,
        prompt_builder: ExamPromptBuilder,
        llm: LLMPort,
    ) -> None:
        self._retriever = retriever
        self._prompt_builder = prompt_builder
        self._llm = llm

    def execute(
        self,
        study_room_id: str,
        multiple_choice: int = 5,
        true_false: int = 3,
        open_questions: int = 2,
    ) -> dict[str, Any]:
        """
        Generates an academic exam using only the
        documents contained in a Study Room.

        Returns:
            Parsed JSON generated by the language model.
        """

        contexts = self._retriever.retrieve(
            question="Generate an academic exam from the available material.",
            study_room_id=study_room_id,
        )

        system_prompt, user_prompt = (
            self._prompt_builder.build(
                contexts=contexts,
                multiple_choice=multiple_choice,
                true_false=true_false,
                open_questions=open_questions,
            )
        )

        response = self._llm.generate(
            prompt=user_prompt,
            system_prompt=system_prompt,
        )

        return JSONParser.parse(
            response,
        )
