from typing import Any

from app.application.ports.llm_port import LLMPort
from app.infrastructure.ai.json_parser import JSONParser
from app.infrastructure.ai.prompts.flashcard_prompt_builder import (
    FlashcardPromptBuilder,
)
from app.infrastructure.ai.rag.retriever import Retriever


class GenerateFlashcardsUseCase:
    """
    Coordinates the complete Retrieval-Augmented Generation
    workflow for generating academic flashcards.
    """

    def __init__(
        self,
        retriever: Retriever,
        prompt_builder: FlashcardPromptBuilder,
        llm: LLMPort,
    ) -> None:
        self._retriever = retriever
        self._prompt_builder = prompt_builder
        self._llm = llm

    def execute(
        self,
        study_room_id: str,
        amount: int = 10,
    ) -> dict[str, Any]:
        """
        Generates study flashcards using only the
        documents contained in a Study Room.

        Returns:
            Parsed JSON generated by the language model.
        """

        contexts = self._retriever.retrieve(
            question="Generate study flashcards from the available material.",
            study_room_id=study_room_id,
        )

        system_prompt, user_prompt = (
            self._prompt_builder.build(
                contexts=contexts,
                amount=amount,
            )
        )

        response = self._llm.generate(
            prompt=user_prompt,
            system_prompt=system_prompt,
        )

        return JSONParser.parse(
            response,
        )
